[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

addopts = 
    --browser chromium
    --screenshot only-on-failure
    --video retain-on-failure
    --html=reports/report.html
    --self-contained-html
    --reruns 2
    --reruns-delay 3
    -p no:baseurl

markers =
    smoke: 冒烟测试
    regression: 回归测试
    singles: 单打模式测试
    doubles: 双打模式测试
    wylb: 五羽伦比测试
